### ISSUE TITLE
ir_%s_sketch do not exist

### ISSUE THREAD

**Issue by Dr-Daniel-Dai** [TengdaHan/Convolutional_Sketch_Inversion#7]
Hi, in ops.py , line 23,  the code wants to read 'ir_%s_sketch', however, make_datafile does not create this file, could you please tell me how to fix it? thank you

**Comment by TengdaHan** [comment]
As I remember, in my project, it should be the line sketch of infrared images, but the infrared image dataset is confidential. Maybe you can see [here](https://github.com/TengdaHan/Convolutional_Sketch_Inversion/tree/master/src/data) to convert your images to line sketch, if it helps.

**Comment by Dr-Daniel-Dai** [comment]
I have prepared the suggested data in your instruction, when I want to train the model, in ops.py , line 23, the code wants to read 'ir_%s_sketch' ,but the file does no exist, so this is the reason for the former question.
By the way,  could you please tell me the version of your keras, I have installed the newest keras, however, keras has updated, and some functions are not working now in the newer version. thanks a lot

**Comment by TengdaHan** [comment]
Q1: I think you have to prepare the dataset for your own purpose and use whatever name.
Q2: I suppose keras version is 1.2.0 or so. Because I did this project in Jan 2017. See [here](https://github.com/keras-team/keras/releases?after=2.0.8)
